### ISSUE TITLE
Account creates Contact

### ISSUE THREAD

**Issue by ricofritzsche** [xptavares/salesmachine-node#2]
Something is wrong in the current version.
This code creates a new contact instead of a new account:

salesmachine.account('432165', {
                                name: "Tesla",
                                employee_count: 1200,
                                website_url: "http://www.teslamotors.com",
                                mrr: 999,
                              }, (err, body) => {
  if(err) {
    return console.error(err.message);
  }
  console.log(body);
})

**Comment by victorcoliveira** [comment]
Same problem here.

lib/account.js Line 7:
`uri: 'https://api.salesmachine.io/v1/contact',`

It should be:
`uri: 'https://api.salesmachine.io/v1/account',`
